# Site settings
title: Source NÂ°1 en Logiciels
email: support@malitech.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: malitech2
github_username: alimakx

# Build settings
markdown: kramdown

plugins:
   - jekyll-language-plugin
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll-include-cache
   - jekyll-analytics
   - jekyll-webp

gems:
   - jekyll-language-plugin
   - jekyll-sitemap
